version: '3.8'

services:

  djangoapp:
    restart: always
    build: .
    command: bash -c "
      while ! nc -z database1 5432; do sleep 1; done;
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py collectstatic --noinput&&
      gunicorn core.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/opt/services/djangoapp/src
      - static_volume:/opt/services/djangoapp/src/static
    networks:
      - nginx_network
      - database1_network
    depends_on:
      - database1

  nginx:
    image: nginx:1.13
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/opt/services/djangoapp/src/static
    depends_on:
      - djangoapp
    networks:
      - nginx_network

  database1:
    restart: always
    image: postgres:10.5
    env_file:
      - config/db/database1_env
    networks:
      - database1_network
    volumes:
      - database1_volume:/var/lib/postgresql/data

networks:
  nginx_network:
    driver: bridge
  database1_network:
    driver: bridge

volumes:
  database1_volume:
  static_volume:
