# Generated by Django 3.2.3 on 2021-05-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earnings_up_to', models.IntegerField(blank=True, null=True)),
                ('percent', models.SmallIntegerField()),
            ],
            options={
                'verbose_name': 'tax band',
                'db_table': 'tax_band',
            },
        ),
    ]
