# Generated by Django 3.1.4 on 2021-05-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0002_load_initial_tax_bands'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxband',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
